title: ""
description: "Contact: hzhan36@gatech.edu"
theme: minima

# minima 主题配置
minima:
  skin: classic    # classic / dark / solarized / solarized-dark

# 导航栏页面
header_pages:
  - index.md
  - pages/about.md
  - pages/resume.md
  - pages/goals.md
  - pages/projects.md

# CSS: assets/css/style.scss

kramdown:
  math_engine: mathjax
