title: Portfolio
description: ECE Student at Georgia Tech
theme: minima

# minima 主题配置
minima:
  skin: classic    # 可选 classic / dark / solarized / solarized-dark

# 导航栏页面
header_pages:
  - assets/pages/about.md
  - assets/pages/resume.md
  - assets/pages/goals.md

# 加你自己的 CSS assets/css/style.scss
